server:
  port: 80
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuhu
    username: root
    password: 123
#mybatis
mybatis:
  type-aliases-package: com.zhihuspider.zhihuspider.model